sude: false
language: cpp
compiler:
    - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - source ./gcc_env.sh
script:
  - gcc -v
  - cc -v
  - g++ -v
  - c++ -v


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8


