sude: false
language: cpp
compiler:
- gcc
env:
  global:
    - CC=/usr/bin/gcc-4.8
    - CXX=/usr/bin/g++-4.8
    - CPP=/usr/bin/cpp-4.8
    - LD=/usr/bin/gcc-4.8

script:
  - gcc -v
  - cc -v
  - g++ -v
  - c++ -v


addons:
  apt:
    sources:
      - 'ppa:ubuntu-toolchain-r/test'
    packages:
      - qq
      - gcc-4.8
      - g++-4.8


