sude: false
language: cpp
compiler:
- gcc

script:
  - source ./gcc_env.sh
  - gcc -v
  - cc -v
  - g++ -v
  - c++ -v


addons:
  apt:
    sources:
      - 'ppa:ubuntu-toolchain-r/test'
    packages:
      - qq
      - gcc-4.8
      - g++-4.8


